files:
  detectors: /database/detectors.csv
  patientSupports: /database/patientSupports.csv
imager:
  fov:
  - 2560
  - 2180
  isocenter:
  - 234.75
  - 572.219
  pixelSize:
  - 0.16
  - 0.16
  sad: 1.2
  sid: 1.5
markers:
  quantity: 3
  size: 2.0
